#!/usr/bin/env sh

GREEN='\033[0;32m'
RED='\033[0;31m'

npx --no -- commitlint --edit "$1" && {
  echo -e "${GREEN}Commit válido. Adelante...${RESET}"
} || {
  echo ""
  echo -e "${RED}Commit inválido. Usa el formato correcto.${RESET}"
  echo -e "- Para más información: https://www.conventionalcommits.org/en/v1.0.0/"
  echo ""
  exit 1
}
