#!/usr/bin/env sh

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

npx --no -- commitlint --edit "$1" && {
  printf "Commit válido. Adelante...${NC}\n"
} || {
  printf "Commit inválido. Usa el formato correcto.${NC}\n"
  echo "- Para más información: https://www.conventionalcommits.org/en/v1.0.0/"
  exit 1
}
