name: Backend CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'sandbox-backend/functions/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'sandbox-backend/functions/**'

jobs:
  release:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: sandbox-backend/functions
        
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.0.0

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint
        
      - name: Build application/backend 
        run: npm run build

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        run: npx semantic-release
