name: Backend CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'sandbox-backend/functions/**'
      - 'sandbox-backend/functions/package.json'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'sandbox-backend/functions/**'
      - 'sandbox-backend/functions/package.json'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.0.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install dependencies
      # 1. elimina carpeta node_modules
      # 3. instala dependencias desde package-lock.json
      # 4. retorna un erorr si no coincide package-lock.json y package.json
      working-directory: sandbox-backend/functions
      run: npm ci

    - name: Lint code
      working-directory: sandbox-backend/functions
      run: npm run lint
      
    - name: Build application/backend 
      working-directory: sandbox-backend/functions
      run: npm run build

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate & Deploy Firebase App
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT" > ${HOME}/gcp-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcp-key.json
        cd sandbox-backend
        firebase deploy --only functions,firestore --project sandbox-ffdff --force

  release:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.0.0]

    defaults:
      run:
        working-directory: sandbox-backend/functions
        
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.0.0

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        run: npx semantic-release
