name: Backend CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'sandbox-backend/functions/**'
      - 'sandbox-backend/functions/package.json'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'sandbox-backend/functions/**'
      - 'sandbox-backend/functions/package.json'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.0.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: sandbox-backend/functions

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install dependencies
      # 1. elimina carpeta node_modules
      # 3. instala dependencias desde package-lock.json
      # 4. retorna un erorr si no coincide package-lock.json y package.json
      run: npm ci

    - name: Lint code
      run: npm run lint
      
    - name: Build application/backend 
      run: npm run build

    - name: Auth & Deploy Fire App
      uses: google-github-actions/deploy-firebase@v0
      with:
        project_id: sandbox-ffdff
        firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        deploy_target: functions,firestore
      env:
        WORKING_DIR: sandbox-backend
