name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'sandbox-frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'sandbox-frontend/**'

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.1]

    defaults:
      run:
        working-directory: sandbox-frontend
        
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test:ci

      - name: Build app
        run: npm run build

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        run: npm run release
